// Event 전용 브랜드 정보 조회
export const GET_EVENT_BRANDS_REQUEST = 'brand/GET_EVENT_BRANDS_REQUEST';
export const GET_EVENT_BRANDS_SUCCESS = 'brand/GET_EVENT_BRANDS_SUCCESS';
export const GET_EVENT_BRANDS_FAILURE = 'brand/GET_EVENT_BRANDS_FAILURE';

export const GET_BRAND_STATISTICS_BRAND_SALES_REQUEST = 'brand/GET_BRAND_STATISTICS_BRAND_SALES_REQUEST';
export const GET_BRAND_STATISTICS_BRAND_SALES_SUCCESS = 'brand/GET_BRAND_STATISTICS_BRAND_SALES_SUCCESS';
export const GET_BRAND_STATISTICS_BRAND_SALES_FAILURE = 'brand/GET_BRAND_STATISTICS_BRAND_SALES_FAILURE';
export const CLEAR_BRAND_SALES_STATUS = 'brand/CLEAR_BRAND_SALES_STATUS';
