// 셀럽리뷰 조회
export const GET_CELEB_REVIEW_REQUEST = 'event/GET_CELEB_REVIEW_REQUEST';
export const GET_CELEB_REVIEW_SUCCESS = 'event/GET_CELEB_REVIEW_SUCCESS';
export const GET_CELEB_REVIEW_FAILURE = 'event/GET_CELEB_REVIEW_FAILURE';

// 셀럽리뷰 수정
export const UPDATE_CELEB_REVIEW_REQUEST = 'event/UPDATE_CELEB_REVIEW_REQUEST';
export const UPDATE_CELEB_REVIEW_SUCCESS = 'event/UPDATE_CELEB_REVIEW_SUCCESS';
export const UPDATE_CELEB_REVIEW_FAILURE = 'event/UPDATE_CELEB_REVIEW_FAILURE';
