// 1:1문의 목록
export const GET_CONTACTS_REQUEST = 'contact/GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'contact/GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILURE = 'contact/GET_CONTACTS_FAILURE';

// 1:1문의 상세
export const GET_CONTACT_REQUEST = 'contact/GET_CONTACT_REQUEST';
export const GET_CONTACT_SUCCESS = 'contact/GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAILURE = 'contact/GET_CONTACT_FAILURE';

// 1:1문의 답글 등록
export const CREATE_CONTACT_COMMENT_REQUEST = 'contact/CREATE_CONTACT_REQUEST';
export const CREATE_CONTACT_COMMENT_SUCCESS = 'contact/CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_COMMENT_FAILURE = 'contact/CREATE_CONTACT_FAILURE';

// 1:1문의 답글 수정
export const UPDATE_CONTACT_COMMENT_REQUEST = 'contact/UPDATE_CONTACT_COMMENT_REQUEST';
export const UPDATE_CONTACT_COMMENT_SUCCESS = 'contact/UPDATE_CONTACT_COMMENT_SUCCESS';
export const UPDATE_CONTACT_COMMENT_FAILURE = 'contact/UPDATE_CONTACT_COMMENT_FAILURE';

// 1:1문의 답글 삭제
export const DELETE_CONTACT_COMMENT_REQUEST = 'contact/DELETE_CONTACT_COMMENT_REQUEST';
export const DELETE_CONTACT_COMMENT_SUCCESS = 'contact/DELETE_CONTACT_COMMENT_SUCCESS';
export const DELETE_CONTACT_COMMENT_FAILURE = 'contact/DELETE_CONTACT_COMMENT_FAILURE';
