// 공구 등록
export const CREATE_EVENT_REQUEST = 'event/CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'event/CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'event/CREATE_EVENT_FAILURE';

// 공구 목록 조회
export const GET_EVENTS_REQUEST = 'event/GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'event/GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'event/GET_EVENTS_FAILURE';

// 공구 조회
export const GET_EVENT_REQUEST = 'event/GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'event/GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'event/GET_EVENT_FAILURE';

// 공구 수정
export const UPDATE_EVENT_REQUEST = 'event/UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'event/UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'event/UPDATE_EVENT_FAILURE';

// 공구 공지 수정
export const UPDATE_EVENT_NOTICES_REQUEST = 'event/UPDATE_EVENT_NOTICES_REQUEST';
export const UPDATE_EVENT_NOTICES_SUCCESS = 'event/UPDATE_EVENT_NOTICES_SUCCESS';
export const UPDATE_EVENT_NOTICES_FAILURE = 'event/UPDATE_EVENT_NOTICES_FAILURE';

// 공구 공지 조회
export const GET_EVENT_NOTICES_REQUEST = 'event/GET_EVENT_NOTICES_REQUEST';
export const GET_EVENT_NOTICES_SUCCESS = 'event/GET_EVENT_NOTICES_SUCCESS';
export const GET_EVENT_NOTICES_FAILURE = 'event/GET_EVENT_NOTICES_FAILURE';

// 공구 오픈
export const UPDATE_EVENT_STATUS_REQUEST = 'event/UPDATE_EVENT_STATUS_REQUEST';
export const UPDATE_EVENT_STATUS_SUCCESS = 'event/UPDATE_EVENT_STATUS_SUCCESS';
export const UPDATE_EVENT_STATUS_FAILURE = 'event/UPDATE_EVENT_STATUS_FAILURE';

// event 초기화
export const CLEAR_EVENT = 'event/CLEAR_EVENT';
