export const CREATE_EVENT_REQUEST = 'event/CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'event/CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'event/CREATE_EVENT_FAILURE';

export const GET_EVENTS_REQUEST = 'event/GET_EVENTS_REQUEST';
export const GET_EVENTS_SUCCESS = 'event/GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'event/GET_EVENTS_FAILURE';

// 셀럽리뷰 수정
export const UPDATE_EVENT_CELEB_REVIEW_REQUEST = 'event/UPDATE_EVENT_CELEB_REVIEW_REQUEST';
export const UPDATE_EVENT_CELEB_REVIEW_SUCCESS = 'event/UPDATE_EVENT_CELEB_REVIEW_SUCCESS';
export const UPDATE_EVENT_CELEB_REVIEW_FAILURE = 'event/UPDATE_EVENT_CELEB_REVIEW_FAILURE';
