export const GET_ORDERS_REQUEST = 'order/GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'order/GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'order/GET_ORDERS_FAILURE';

export const GET_ORDERS_EXCEL_REQUEST = 'order/GET_ORDERS_EXCEL_REQUEST';
export const GET_ORDERS_EXCEL_SUCCESS = 'order/GET_ORDERS_EXCEL_SUCCESS';
export const GET_ORDERS_EXCEL_FAILURE = 'order/GET_ORDERS_EXCEL_FAILURE';
