export const GET_ORDERS_REQUEST = 'order/GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'order/GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'order/GET_ORDERS_FAILURE';

export const UPDATE_ORDERS_PAYMENT_STATUS_REQUEST = 'payment/UPDATE_ORDERS_PAYMENT_STATUS_REQUEST';
export const UPDATE_ORDERS_PAYMENT_STATUS_SUCCESS = 'payment/UPDATE_ORDERS_PAYMENT_STATUS_SUCCESS';
export const UPDATE_ORDERS_PAYMENT_STATUS_FAILURE = 'payment/UPDATE_ORDERS_PAYMENT_STATUS_FAILURE';

export const GET_ORDERS_EXCEL_REQUEST = 'order/GET_ORDERS_EXCEL_REQUEST';
export const GET_ORDERS_EXCEL_SUCCESS = 'order/GET_ORDERS_EXCEL_SUCCESS';
export const GET_ORDERS_EXCEL_FAILURE = 'order/GET_ORDERS_EXCEL_FAILURE';

export const GET_ORDERS_STATISTICS_DAILY_SALES_REQUEST = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_REQUEST';
export const GET_ORDERS_STATISTICS_DAILY_SALES_SUCCESS = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_SUCCESS';
export const GET_ORDERS_STATISTICS_DAILY_SALES_FAILURE = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_FAILURE';

export const CLEAR_DAILY_SALES_STATUS = 'order/CLEAR_DAILY_SALES_STATUS';