export const GET_ORDERS_REQUEST = 'order/GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'order/GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'order/GET_ORDERS_FAILURE';

export const GET_ORDERS_EXCEL_REQUEST = 'order/GET_ORDERS_EXCEL_REQUEST';
export const GET_ORDERS_EXCEL_SUCCESS = 'order/GET_ORDERS_EXCEL_SUCCESS';
export const GET_ORDERS_EXCEL_FAILURE = 'order/GET_ORDERS_EXCEL_FAILURE';

export const GET_ORDERS_STATISTICS_DAILY_SALES_REQUEST = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_REQUEST';
export const GET_ORDERS_STATISTICS_DAILY_SALES_SUCCESS = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_SUCCESS';
export const GET_ORDERS_STATISTICS_DAILY_SALES_FAILURE = 'order/GET_ORDERS_STATISTICS_DAILY_SALES_FAILURE';

export const GET_ORDER_BY_ID_REQUEST = 'order/GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS = 'order/GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FAILURE = 'order/GET_ORDER_BY_ID_FAILURE';



export const UPDATE_SHIPPING_DESTINATION_BY_ID_REQUEST = 'order/UPDATE_SHIPPING_DESTINATION_BY_ID_REQUEST';
export const UPDATE_SHIPPING_DESTINATION_BY_ID_SUCCESS = 'order/UPDATE_SHIPPING_DESTINATION_BY_ID_SUCCESS';
export const UPDATE_SHIPPING_DESTINATION_BY_ID_FAILURE = 'order/UPDATE_SHIPPING_DESTINATION_BY_ID_FAILURE';

export const CLEAR_DAILY_SALES_STATUS = 'order/CLEAR_DAILY_SALES_STATUS';

export const CLEAR_ORDER_EXCEL = 'order/CLEAR_ORDER_EXCEL';

export const CLEAR_ORDER = 'order/CREAR_ORDER';

export const UPDATE_ORDERS_PAYMENT_STATUS_REQUEST = 'order/UPDATE_ORDERS_PAYMENT_STATUS_REQUEST';
export const UPDATE_ORDERS_PAYMENT_STATUS_SUCCESS = 'order/UPDATE_ORDERS_PAYMENT_STATUS_SUCCESS';
export const UPDATE_ORDERS_PAYMENT_STATUS_FAILURE = 'order/UPDATE_ORDERS_PAYMENT_STATUS_FAILURE';

export const CANCEL_PAYMENT_VIRTUAL_ACCOUNT_REQUEST = 'order/CANCEL_PAYMENT_VIRTUAL_ACCOUNT_REQUEST';
export const CANCEL_PAYMENT_VIRTUAL_ACCOUNT_SUCCESS = 'order/CANCEL_PAYMENT_VIRTUAL_ACCOUNT_SUCCESS';
export const CANCEL_PAYMENT_VIRTUAL_ACCOUNT_FAILURE = 'order/CANCEL_PAYMENT_VIRTUAL_ACCOUNT_FAILURE';

export const CANCEL_PAYMENT_REQUEST = 'order/CANCEL_PAYMENT_REQUEST';
export const CANCEL_PAYMENT_SUCCESS = 'order/CANCEL_PAYMENT_SUCCESS';
export const CANCEL_PAYMENT_FAILURE = 'order/CANCEL_PAYMENT_FAILURE';

export const CHECK_REFUND_ACCOUNT_REQUEST = 'order/CHECK_REFUND_ACCOUNT_REQUEST';
export const CHECK_REFUND_ACCOUNT_SUCCESS = 'order/CHECK_REFUND_ACCOUNT_SUCCESS';
export const CHECK_REFUND_ACCOUNT_FAILURE = 'order/CHECK_REFUND_ACCOUNT_FAILURE';

export const RESET_REFUND_ACCOUNT_STATE_REDUCER = 'order/RESET_REFUND_ACCOUNT_STATE_REDUCER';

// 가상계좌 입금 대기 취소
export const CANCEL_VIRTUAL_ACCOUNT_WAITING_REQUEST = 'order/CANCEL_VIRTUAL_ACCOUNT_WAITING_REQUEST';
export const CANCEL_VIRTUAL_ACCOUNT_WAITING_SUCCESS = 'order/CANCEL_VIRTUAL_ACCOUNT_WAITING_SUCCESS';
export const CANCEL_VIRTUAL_ACCOUNT_WAITING_FAILURE = 'order/CANCEL_VIRTUAL_ACCOUNT_WAITING_FAILURE';

