export const CREATE_ORDER_MEMO_REQUEST = 'orderMemo/CREATE_ORDER_MEMO_REQUEST';
export const CREATE_ORDER_MEMO_SUCCESS = 'orderMemo/CREATE_ORDER_MEMO_SUCCESS';
export const CREATE_ORDER_MEMO_FAILURE = 'orderMemo/CREATE_ORDER_MEMO_FAILURE';

export const GET_ORDER_MEMOS_REQUEST = ''