// 공구 정보 조회 (추후 공구와 취합해야함)
export const GET_EVENT_REQUEST = 'event/GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'event/GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'event/GET_EVENT_FAILURE';

// 배송비 설정 변경 (추후 공구와 취합해야함)
export const UPDATE_SHIPPING_FEE_INFO_REQUEST = 'event/UPDATE_SHIPPING_FEE_INFO_REQUEST';
export const UPDATE_SHIPPING_FEE_INFO_SUCCESS = 'event/UPDATE_SHIPPING_FEE_INFO_SUCCESS';
export const UPDATE_SHIPPING_FEE_INFO_FAILURE = 'event/UPDATE_SHIPPING_FEE_INFO_FAILURE';

// 제품 생성
export const CREATE_PRODUCTS_REQUEST = 'product/CREATE_PRODUCTS_REQUEST';
export const CREATE_PRODUCTS_SUCCESS = 'product/CREATE_PRODUCTS_SUCCESS';
export const CREATE_PRODUCTS_FAILURE = 'product/CREATE_PRODUCTS_FAILURE';

// 제품 수정
export const UPDATE_PRODUCTS_REQUEST = 'product/UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCTS_SUCCESS = 'product/UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAILURE = 'product/UPDATE_PRODUCTS_FAILURE';

// 제품 삭제
export const DELETED_PRODUCTS_REQUEST = 'product/DELETED_PRODUCTS_REQUEST';
export const DELETED_PRODUCTS_SUCCESS = 'product/DELETED_PRODUCTS_SUCCESS';
export const DELETED_PRODUCTS_FAILURE = 'product/DELETED_PRODUCTS_FAILURE';

// 제품 품절 처리
export const SOLD_OUT_PRODUCTS_REQUEST = 'product/SOLD_OUT_PRODUCTS_REQUEST';
export const SOLD_OUT_PRODUCTS_SUCCESS = 'product/SOLD_OUT_PRODUCTS_SUCCESS';
export const SOLD_OUT_PRODUCTS_FAILURE = 'product/SOLD_OUT_PRODUCTS_FAILURE';