// 제품 생성
import { createAsyncAction } from 'typesafe-actions';
import * as Actions from './orderAction';
import { ErrorAsyncAction, RequestAsyncAction, ResponseAsyncAction } from '../../models';

export const CREATE_PRODUCTS_REQUEST = 'product/CREATE_PRODUCTS_REQUEST';
export const CREATE_PRODUCTS_SUCCESS = 'product/CREATE_PRODUCTS_SUCCESS';
export const CREATE_PRODUCTS_FAILURE = 'product/CREATE_PRODUCTS_FAILURE';

// 제품 수정
export const UPDATE_PRODUCTS_REQUEST = 'product/UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCTS_SUCCESS = 'product/UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCTS_FAILURE = 'product/UPDATE_PRODUCTS_FAILURE';

// 제품 삭제
export const DELETED_PRODUCTS_REQUEST = 'product/DELETED_PRODUCTS_REQUEST';
export const DELETED_PRODUCTS_SUCCESS = 'product/DELETED_PRODUCTS_SUCCESS';
export const DELETED_PRODUCTS_FAILURE = 'product/DELETED_PRODUCTS_FAILURE';

// 제품 품절 처리
export const SOLD_OUT_PRODUCTS_REQUEST = 'product/SOLD_OUT_PRODUCTS_REQUEST';
export const SOLD_OUT_PRODUCTS_SUCCESS = 'product/SOLD_OUT_PRODUCTS_SUCCESS';
export const SOLD_OUT_PRODUCTS_FAILURE = 'product/SOLD_OUT_PRODUCTS_FAILURE';

// 제품 통계 조회
export const STATISTICS_PRODUCTS_REQUEST = 'product/STATISTICS_PRODUCTS_REQUEST';
export const STATISTICS_PRODUCTS_SUCCESS = 'product/STATISTICS_PRODUCTS_SUCCESS';
export const STATISTICS_PRODUCTS_FAILURE = 'product/STATISTICS_PRODUCTS_FAILURE';
export const CLEAR_PRODUCT_SALES_STATUS = 'product/CLEAR_PRODUCT_SALES_STATUS';

// 제품 통계 Excel 다운로드
export const STATISTICS_PRODUCTS_EXCEL_REQUEST = 'product/STATISTICS_PRODUCTS_EXCEL_REQUEST';
export const STATISTICS_PRODUCTS_EXCEL_SUCCESS = 'product/STATISTICS_PRODUCTS_EXCEL_SUCCESS';
export const STATISTICS_PRODUCTS_EXCEL_FAILURE = 'product/STATISTICS_PRODUCTS_EXCEL_FAILURE';
export const CLEAR_PRODUCT_SALES_EXCEL_STATUS = 'product/CLEAR_PRODUCT_SALES_EXCEL_STATUS';

// 상품 정보 생성
export const CREATE_PRODUCT_NOTICE_REQUEST = 'product/PRODUCT_NOTICE_REQUEST';
export const CREATE_PRODUCT_NOTICE_SUCCESS = 'product/PRODUCT_NOTICE_REQUEST';
export const CREATE_PRODUCT_NOTICE_FAILURE = 'product/PRODUCT_NOTICE_REQUEST';

// 상품 정보 수정
export const UPDATE_PRODUCT_NOTICE_REQUEST = 'product/PRODUCT_NOTICE_REQUEST';
export const UPDATE_PRODUCT_NOTICE_SUCCESS = 'product/PRODUCT_NOTICE_REQUEST';
export const UPDATE_PRODUCT_NOTICE_FAILURE = 'product/PRODUCT_NOTICE_REQUEST';

// 상품 정보 수정
export const DELETED_PRODUCT_NOTICE_REQUEST = 'product/PRODUCT_NOTICE_REQUEST';
export const DELETED_PRODUCT_NOTICE_SUCCESS = 'product/PRODUCT_NOTICE_REQUEST';
export const DELETED_PRODUCT_NOTICE_FAILURE = 'product/PRODUCT_NOTICE_REQUEST';