export const GET_QNA_REQUEST = 'qna/GET_QNA_REQUEST';
export const GET_QNA_SUCCESS = 'qna/GET_QNA_SUCCESS';
export const GET_QNA_FAILURE = 'qna/GET_QNA_FAILURE';

export const CREATE_QNA_COMMENT_REQUEST = 'qna/CREATE_QNA_COMMENT_REQUEST';
export const CREATE_QNA_COMMENT_SUCCESS = 'qna/CREATE_QNA_COMMENT_SUCCESS';
export const CREATE_QNA_COMMENT_FAILURE = 'qna/CREATE_QNA_COMMENT_FAILURE';

export const UPDATE_QNA_COMMENT_REQUEST = 'qna/UPDATE_QNA_COMMENT_REQUEST';
export const UPDATE_QNA_COMMENT_SUCCESS = 'qna/UPDATE_QNA_COMMENT_SUCCESS';
export const UPDATE_QNA_COMMENT_FAILURE = 'qna/UPDATE_QNA_COMMENT_FAILURE';

export const DELETE_QNA_COMMENT_REQUEST = 'qna/DELETE_QNA_COMMENT_REQUEST';
export const DELETE_QNA_COMMENT_SUCCESS = 'qna/DELETE_QNA_COMMENT_SUCCESS';
export const DELETE_QNA_COMMENT_FAILURE = 'qna/DELETE_QNA_COMMENT_FAILURE';

export const UPDATE_QNA_EXPOSE_REQUEST = 'qna/UPDATE_QNA_EXPOSE_REQUEST';
export const UPDATE_QNA_EXPOSE_SUCCESS = 'qna/UPDATE_QNA_EXPOSE_SUCCESS';
export const UPDATE_QNA_EXPOSE_FAILURE = 'qna/UPDATE_QNA_EXPOSE_FAILURE';
