// 목록 조회
export const GET_REVIEWS_REQUEST = 'review/GET_REVIEWS_REQUEST';
export const GET_REVIEWS_SUCCESS = 'review/GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'review/GET_REVIEWS_FAILURE';

// 단건 조회
export const GET_REVIEW_REQUEST = 'review/GET_REVIEW_REQUEST';
export const GET_REVIEW_SUCCESS = 'review/GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAILURE = 'review/GET_REVIEW_FAILURE';

// 수정
export const UPDATE_REVIEW_REQUEST = 'review/UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'review/UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'review/UPDATE_REVIEW_FAILURE';

// 숨김/공개
export const UPDATE_REVIEW_EXPOSE_REQUEST = 'review/UPDATE_REVIEW_EXPOSE_REQUEST';
export const UPDATE_REVIEW_EXPOSE_SUCCESS = 'review/UPDATE_REVIEW_EXPOSE_SUCCESS';
export const UPDATE_REVIEW_EXPOSE_FAILURE = 'review/UPDATE_REVIEW_EXPOSE_FAILURE';

// 숨김/공개(multi)
export const UPDATE_REVIEWS_EXPOSE_REQUEST = 'review/UPDATE_REVIEW_EXPOSEREQUEST';
export const UPDATE_REVIEWS_EXPOSE_SUCCESS = 'review/UPDATE_REVIEW_EXPOSESUCCESS';
export const UPDATE_REVIEWS_EXPOSE_FAILURE = 'review/UPDATE_REVIEW_EXPOSEFAILURE';
