export const GET_SHIPPING_REQUEST = 'shipping/GET_SHIPPING_REQUEST';
export const GET_SHIPPING_SUCCESS = 'shipping/GET_SHIPPING_SUCCESS';
export const GET_SHIPPING_FAILURE = 'shipping/GET_SHIPPING_FAILURE';

export const UPDATE_SHIPPING_REQUEST = 'shipping/UPDATE_SHIPPING_REQUEST';
export const UPDATE_SHIPPING_SUCCESS = 'shipping/UPDATE_SHIPPING_SUCCESS';
export const UPDATE_SHIPPING_FAILURE = 'shipping/UPDATE_SHIPPING_FAILURE';

export const UPDATE_SHIPPING_STATUS_REQUEST = 'shipping/UPDATE_SHIPPING_STATUS_REQUEST';
export const UPDATE_SHIPPING_STATUS_SUCCESS = 'shipping/UPDATE_SHIPPING_STATUS_SUCCESS';
export const UPDATE_SHIPPING_STATUS_FAILURE = 'shipping/UPDATE_SHIPPING_STATUS_FAILURE';

export const GET_SHIPPING_EXCEL_REQUEST = 'shipping/GET_SHIPPING_EXCEL_REQUEST';
export const GET_SHIPPING_EXCEL_SUCCESS = 'shipping/GET_SHIPPING_EXCEL_SUCCESS';
export const GET_SHIPPING_EXCEL_FAILURE = 'shipping/GET_SHIPPING_EXCEL_FAILURE';

export const UPDATE_EXCEL_INVOICE_REQUEST = 'shipping/UPDATE_EXCEL_INVOICE_REQUEST';
export const UPDATE_EXCEL_INVOICE_SUCCESS = 'shipping/UPDATE_EXCEL_INVOICE_SUCCESS';
export const UPDATE_EXCEL_INVOICE_FAILURE = 'shipping/UPDATE_EXCEL_INVOICE_FAILURE';

export const CLEAR_SHIPPING_EXCEL = 'shipping/CLEAR_SHIPPING_EXCEL';
