export const GET_SHIPPING_REQUEST = 'shipping/GET_SHIPPING_REQUEST';
export const GET_SHIPPING_SUCCESS = 'shipping/GET_SHIPPING_SUCCESS';
export const GET_SHIPPING_FAILURE = 'shipping/GET_SHIPPING_FAILURE';

export const UPDATE_SHIPPING_REQUEST = 'shipping/UPDATE_SHIPPING_REQUEST';
export const UPDATE_SHIPPING_SUCCESS = 'shipping/UPDATE_SHIPPING_SUCCESS';
export const UPDATE_SHIPPING_FAILURE = 'shipping/UPDATE_SHIPPING_FAILURE';
