export const productNoticeType = [
  { text: '선택', value: '' },
  { text: '의류', value: 'CLOTHING' },
  { text: '구두/신발', value: 'SHOES' },
  { text: '가방', value: 'BAG' },
  { text: '패션잡화', value: 'FASHION_ITEM' },
  { text: '가전기기', value: 'HOUSEHOLD_ELECTRICAL_APPLIANCES' },
  { text: '소형전자 ', value: 'MINIATURE_ELECTRON' },
  { text: '의료기기', value: 'MEDICAL_APPLIANCES' },
  { text: '화장품', value: 'COSMETICS' },
  { text: '귀금속/보석/시계류', value: 'DECORATIVE_ITEM' },
  { text: '가공식품', value: 'PROCESSED_FOOD' },
  { text: '건강기능식품', value: 'HEALTH_FOOD' },
  { text: '영유아용품', value: 'INFANT_ITEM' },
  { text: '스포츠용품', value: 'SPORTS_ITEM' },
  { text: '기타 재화', value: 'ETC' },
];

export const productProvision = {
  CLOTHING: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    {
      title: '제품 소재',
      desc: '* 섬유의 조성 또는 혼용률을 백분율로 표기\n* 기능성인 경우 성적서 또는 허가서 내용 표기',
      key: 'material',
    },
    {
      title: '색상',
      desc:
        '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능\n',
      key: 'color',
    },
    { title: '치수', desc: '* ‘90, 95, 100’ 또는 ‘S, M, L’ 처럼 문자 표시 가능\n', key: 'size' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '세탁방법 및 취급시 주의 사항', desc: '', key: 'handlingSafetyPrecautions' },
    {
      title: '제조 연월',
      desc:
        '* 예시) 2019년 7월\n* 제조년월을 확인할 수 없는 경우 그에 대한 이유를 표시하고 최초 판매시즌, 로트번호 표시로 대체 가능\n',
      key: 'manufacturingDate',
    },
    { title: '품질 보증 기준', desc: '*예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    {
      title: 'A/S 책임자와 전화번호',
      desc: '*담당자 표기가 어려운 경우, 업페의 업체명 및 연락처 표',
      key: 'serviceManagerNumber',
    },
  ],
  PROCESSED_FOOD: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '식품의 유형', desc: '', key: 'foodType' },
    { title: '생산자 및 소재지', desc: '* 피부타입, 색상(호, 번) 등', key: 'manufacturerCountry' },
    { title: '제조연월일, 유통기한 또는 품질유지기한', desc: '* 개봉 후 사용기간을 기재할 경우에는 제조연월일도 표기', key: 'manufacturingDate' },
    { title: '포장단위별 용량(중량), 수량', desc: '', key: 'weight' },
    { title: '원재료명 및 함량', desc: '', key: 'rawMaterialContent' },
    { title: '영양성분', desc: '', key: 'nutritionalInformation' },
    { title: '유전자변형식품에 해당하는 경우의 표시', desc: '* 표시 대상 여부를 반드시 표기하여야 함. 대상이 아닌 경우 ‘해당없음’으로 표기', key: 'transgenic' },
    {
      title: '영유아식 또는 체중조절식품에 해당하는 경우 표기광고사전심의필 유무 및 부작용 발생 가능성',
      desc: '* 심의 유무와 사전심의번호 함께 표시, 별도 이미지 표시하지 않아도 됨',
      key: 'notationAdvertisementSideEffectOccurrence',
    },
    {
      title: '수입식품에 해당하는 경우 “식품위생법에 따른 수입신고를 필함”의 문구',
      desc: '',
      key: 'importedFoodMedicineLaw',
    },
    { title: '소비자상담 관련 전화번호', desc: '', key: 'consumerConsultationNumber' },
  ],
  SHOES: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '제품 주 소재', desc: '* 운동화의 경우에는 겉감, 안감을 구분하여 표기', key: 'material' },
    { title: '색상',
      desc: '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n' +
        '* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능',
      key: 'color' },
    { title: '치수',
      desc: '* 발길이(mm), 굽높이(cm, 해당하는 경우 표기)\n' +
        '* 해외 사이즈 표기시 국내사이즈 병행 표기(mm)',
      key: 'size' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '취급시 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  BAG: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '종류', desc: '* 예시) 숄더백, 백팩, 서류가방 등', key: 'kind' },
    { title: '소재', desc: '', key: 'material' },
    { title: '색상',
      desc: '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n' +
        '* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능',
      key: 'color' },
    { title: '크기', desc: '* 가로, 세로, 끈길이 등 제품의 크기 정보 표기', key: 'size' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '취급시 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  FASHION_ITEM: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '종류', desc: '', key: 'kind' },
    { title: '소재', desc: '', key: 'material' },
    { title: '치수', desc: '', key: 'size' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '취급시 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  HOUSEHOLD_ELECTRICAL_APPLIANCES: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: 'KC 인증 필 유무', desc: '* 전파법 상 인증대상상품에 한함. MIC 인증 필 혼용 가능', key: 'kcCertified' },
    { title: '정격전압, 소비전력', desc: '* 인증 대상상품일 경우 인증번호 등 관련 정보 표기\n' +
        '* 확인할 수 없는 경우는 ‘확인할 수 없음’, 대상이 아닌 경우는 ‘대상 아님’으로 표기', key: 'voltagePowerConsumption' },
    { title: '에너지소비효율등급', desc: '* 에너지이용합리화법 상 의무대상상품에 한함', key: 'energyConsumptionRating' },
    { title: '동일모델의 출시년월', desc: '* 예) 2019년 1월', key: 'sameModelLaunchDate' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '크기, 무게', desc: '* 가로/세로/높이 입력(단위 표시), 용량/형태 포함하여 입력', key: 'weight' },
    { title: '제품 주요 사항', desc: '', key: 'majorIssue' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  MINIATURE_ELECTRON: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: 'KC 인증 필 유무', desc: '* 전파법 상 인증대상상품에 한함. MIC 인증 필 혼용 가능', key: 'kcCertified' },
    { title: '정격전압, 소비전력', desc: '* 인증 대상상품일 경우 인증번호 등 관련 정보 표기\n' +
        '* 확인할 수 없는 경우는 ‘확인할 수 없음’, 대상이 아닌 경우는 ‘대상 아님’으로 표기', key: 'voltagePowerConsumption' },
    { title: '동일모델의 출시년월', desc: '* 예) 2019년 1월', key: 'sameModelLaunchDate' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '크기, 무게', desc: '', key: 'weight' },
    { title: '제품 주요 사항', desc: '', key: 'majorIssue' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  MEDICAL_APPLIANCES: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '의료기기법상 허가・신고 번호 및 광고사전심의필 유무',
      desc: '* 의료기기일 경우 허가·신고 번호 표기하고 광고사전심의번호 필수 표기\n' +
        '* 확인할 수 없는 경우는 ‘확인할 수 없음’, 대상이 아닌 경우는 ‘대상 아님’으로 표기',
      key: 'medicalPermissionReportNumber' },
    { title: 'KC 인증 필 유무',
      desc: '* 인증 대상상품일 경우 인증번호 등 관련 정보 표기\n' +
        '* 확인할 수 없는 경우는 ‘확인할 수 없음’, 대상이 아닌 경우는 ‘대상 아님’으로 표기',
      key: 'kcCertified' },
    { title: '정격전압, 소비전력', desc: '* 전기용품에 한함', key: 'voltagePowerConsumption' },
    { title: '동일모델의 출시년월', desc: '* 예시) 2019년 8월', key: 'sameModelLaunchDate' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '제품의 사용목적 및 사용 방법', desc: '', key: 'usePurposeHow' },
    { title: '취급시 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  COSMETICS: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '용량 또는 중량', desc: '', key: 'weight' },
    { title: '제품 주요 사항', desc: '* 피부타입, 색상(호, 번) 등', key: 'majorIssue' },
    { title: '사용기한 또는 개봉 후 사용 기간', desc: '* 개봉후 사용기간 표기시 제조연월일 병행표기', key: 'useDeadLine' },
    { title: '사용방법', desc: '', key: 'usePurposeHow' },
    { title: '제조업자 및 책임(제조) 판매업자', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '화장품법에 따라 기재・표시하여야 하는 모든 성분', desc: '', key: 'ingredient' },
    {
      title: '기능성 화장품의 경우 화장품법에 따른 식품의약품안전처 심사 필 유무',
      desc: '* 백, 주름개선, 자외선차단 등 해당 해당사항 없는 경우, "해당사항 없음"으로 표기',
      key: 'foodMedicineSafetyAudit',
    },
    { title: '사용할 때 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: '소비자상담관련 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  DECORATIVE_ITEM: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '소재/순도/밴드재질', desc: '* 밴드는 시계의 경우에만 표기', key: 'material' },
    { title: '중량', desc: '', key: 'weight' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '치수', desc: '', key: 'size' },
    { title: '착용 시 주의사항', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '귀금속 보석류 주요 사양(등급)', desc: '', key: 'jewelryMainSpecification' },
    { title: '시계 주요 사양', desc: '* 기능, 방수 등', key: 'clockMainSpecification' },
    { title: '보증서 제공 여부', desc: '', key: 'guaranteeProvision' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  HEALTH_FOOD: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '식품의 유형', desc: '', key: 'foodType' },
    { title: '제조업소의 명칭과 소재지', desc: '* 수입품의 경우 수입업소명, 제조업소명 및 수출국명 표기', key: 'manufacturerCountry' },
    { title: '제조연월일, 유통기한 또는 품질유지기한', desc: '', key: 'manufacturingDate' },
    { title: '포장단위별 용량(중량), 수량', desc: '', key: 'weight' },
    { title: '원재료명 및 함량', desc: '', key: 'rawMaterialContent' },
    { title: '영양정보', desc: '', key: 'nutritionalInformation' },
    { title: '기능정보', desc: '', key: 'functionalInformation' },
    {
      title: '섭취량, 섭취방법 및 섭취시 주의사항 및 부작용 가능성',
      desc: '',
      key: 'diseaseTreatmentMedicationNotContent',
    },
    { title: '질병의 예방 및 치료를 위한 의약품이 아니라는 내용의 표현', desc: '* 예시) 본 제품은 질벼의 예방 및 치료를 위한 위약품이 아닙니다.', key: 'handlingSafetyPrecautions' },
    { title: '유전자변형건강기능식품에 해당하는 경우 표시', desc: '* 해당사항 없음" 혹은 "유전자재조합식품" 표기', key: 'transgenic' },
    { title: '표시광고 사전심의필', desc: '* “심의필” 및 심의번호 표기', key: 'notationAdvertisementSideEffectOccurrence' },
    {
      title: '수입식품에 해당하는 경우 “건강기능식품에 관한 법률에 따른 수입신고를 필함”의 문구',
      desc: '* 수입 식품인 경우에만 문구 표기, 해당 사항이 없을 경우 “해당사항 없음” 표기',
      key: 'importedFoodMedicineLaw',
    },
  ],
  INFANT_ITEM: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: 'KC인증 필 유무', desc: '* 어린이제품 안전 특별법 상 안전인증대상어린이제품, 안전확인대상어린이제품에 한해 표기', key: 'kcCertified' },
    { title: '크기, 중량', desc: '', key: 'weight' },
    { title: '색상',
      desc: '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n' +
        '* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능',
      key: 'color' },
    { title: '재질', desc: '* 섬유의 경우 혼용률 표기', key: 'material' },
    { title: '사용연령 또는 체중범위', desc: '* 어린이제품 안전 특별법에 따라 표시해야 하는 사항은 반드시 표기', key: 'ageOfUseOrWeightRange' },
    { title: '동일모델의 출시년월', desc: '', key: 'sameModelLaunchDate' },
    { title: '제조자(수입자)', desc: '* 병행수입의 경우 병행수입 여부로 대체 가능', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '취급방법 및 취급시 주의사항, 안전표시', desc: '', key: 'handlingSafetyPrecautions' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  SPORTS_ITEM: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    { title: '크기, 중량', desc: '', key: 'weight' },
    { title: '색상',
      desc: '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n' +
        '* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능',
      key: 'color' },
    { title: '재질', desc: '', key: 'material' },
    { title: '제품 구성', desc: '', key: 'configuration' },
    { title: '동일모델의 출시년월', desc: '* 예시) 2019년 9월', key: 'sameModelLaunchDate' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: '제조국', desc: '', key: 'manufacturerCountry' },
    { title: '상품별 세부 사양', desc: '', key: 'detailSpecification' },
    { title: '품질 보증 기준', desc: '* 예시) 관련법 및 소비자분쟁해결 기준에 따름', key: 'qualityAssuranceCriteria' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
  ETC: [
    { title: '아이디', desc: '', key: 'productProvisionId' },
    { title: '품목 및 모델명', desc: '', key: 'modelName' },
    {
      title: '법에 의한 인증・허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항',
      desc: '',
      key: 'legalCertification',
    },
    { title: '제조국 또는 원산지',
      desc: '* 두 가지 이상일 경우라도 대표 색상 표기 가능\n' +
        '* 여러 색상을 포함한 경우 주된 색상을 기재하거나 ‘사진참조 등’으로 기재 가능',
      key: 'manufacturerCountry' },
    { title: '제조자(수입자)', desc: '', key: 'manufacturer' },
    { title: 'A/S 책임자와 전화번호', desc: '* 담당자 표기가 어려운 경우, 업체의 업체명 및 연락처 표기', key: 'serviceManagerNumber' },
  ],
};

export const productProvisionData = {
  ageOfUseOrWeightRange: '',
  clockMainSpecification: '',
  color: '',
  configuration: '',
  consumerConsultationNumber: '',
  detailSpecification: '',
  diseaseTreatmentMedicationNotContent: '',
  foodMedicineSafetyAudit: '',
  foodType: '',
  functionalInformation: '',
  guaranteeProvision: '',
  handlingSafetyPrecautions: '',
  importedFoodMedicineLaw: '',
  ingredient: '',
  jewelryMainSpecification: '',
  kcCertified: '',
  kind: '',
  legalCertification: '',
  majorIssue: '',
  manufacturer: '',
  manufacturerCountry: '',
  manufacturingDate: '',
  material: '',
  medicalPermissionReportNumber: '',
  modelName: '',
  notationAdvertisementSideEffectOccurrence: '',
  nutritionalInformation: '',
  productProvisionId: null,
  qualityAssuranceCriteria: '',
  rawMaterialContent: '',
  sameModelLaunchDate: '',
  serviceManagerNumber: '',
  size: '',
  transgenic: '',
  useDeadLine: '',
  usePurposeHow: '',
  voltagePowerConsumption: '',
  weight: '',
  energyConsumptionRating:'',
};
